# Generated by Django 2.2.4 on 2019-09-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gif_type',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
