# Generated by Django 2.2.4 on 2019-09-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_image_gif_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='gif_type',
            new_name='type',
        ),
    ]
