# Generated by Django 2.2.4 on 2019-09-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_auto_20190914_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='s3_uuid',
        ),
        migrations.AddField(
            model_name='image',
            name='s3_key',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
