# Generated by Django 2.2.4 on 2019-11-18 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0007_framedata_imagedata_trackedelement_trackedelementadjustment_trackedelementposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedelementposition',
            name='frame_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gifs.FrameData'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='background_image_path',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='foreground_image_path',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
