# Generated by Django 2.2.4 on 2019-11-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0009_auto_20191118_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='framedata',
            name='has_foreground',
            field=models.BooleanField(default=False),
        ),
    ]
