# Generated by Django 2.2.4 on 2019-11-18 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0010_framedata_has_foreground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedelementposition',
            name='tracked_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gifs.TrackedElement'),
        ),
    ]
